language: php

php:
  # see http://php.net/supported-versions.php
  - '7.3' # Until 6 Dec 2021
  - '7.4' # Until 28 Nov 2022
  - '8.0' # Until 26 Nov 2023

env:
  global:
    - COMPOSER_CACHE_DIR=/home/travis/.composer
    - XDEBUG_MODE=coverage
  matrix:
    # see https://phpunit.de/supported-versions.html
    - PHPUNIT_VERSION=8.5.*
    - PHPUNIT_VERSION=9.5.*

matrix:
  # These are the major scenarios
  # See https://packagist.org/packages/phpunit/phpunit#6.5.14
  # We use the minimum PHP version.
  include:
    - php: '7.0'
      env: PHPUNIT_VERSION=6.5.*
    - php: '7.1'
      env: PHPUNIT_VERSION=7.5.*
    - php: '7.2'
      env: PHPUNIT_VERSION=8.5.*
    - php: '7.3'
      env: PHPUNIT_VERSION=8.0.*
    - php: '7.4'
      env: PHPUNIT_VERSION=8.5.*
    - php: '8.0'
      env: PHPUNIT_VERSION=8.5.*
    - php: '8.0'
      env: PHPUNIT_VERSION=8.4.*

    # We add some tests here for that we want to achieve or keep compatibility.
    # Some are made due to unstable SemVer of testing packages (guess which).

    - php: 'hhvm'
      env: PHPUNIT_VERSION=7.*
    # Check with latest PHP version (using a working WP version)
    - php: 'nightly'
      env: PHPUNIT_VERSION=7.*
    # Check with nightly build of WordPress (using a working PHP version)
    - php: 7.4
      env: PHPUNIT_VERSION=dev-master
  # all above are allowed to fail because they just check the compatibility
  allow_failures:
    - php: '5.6'
    - php: 'hhvm'
    - php: 'nightly'
    - env: PHPUNIT_VERSION=dev-master
  # Do not wait for allowed failures
  fast_finish: true

cache:
  directories:
    - /home/travis/.composer

before_install:
  # Try supporting other versions
  - "[[ $PHPUNIT_VERSION != *'dev-master' ]] || composer config minimum-stability dev"
  - "[[ $PHPUNIT_VERSION != *'dev-master' ]] || composer config prefer-stable true"
  - composer require --update-with-dependencies phpunit/phpunit:$PHPUNIT_VERSION

install:
  - composer install

script:
  - "[[ $PHPUNIT_VERSION == *'dev-master' ]] || composer validate --strict --no-check-lock"
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - vendor/bin/coveralls --verbose
