stages:
  # first QA because if those basics things don't work
  # then we don't waste more runtime for it.
  - qa
  - test
  # The "compat" pipeline contains old things that may be dropped
  # and new things that we try to achieve.
  # We try to keep up backward compatibility
  # (e.g. for deprecated PHP versions) as long as possible,
  # because this package may be used by others to test old stuff.
  #
  #
  # see https://www.php.net/supported-versions.php
  # see https://www.php.net/eol.php
  # see https://codex.wordpress.org/WordPress_Versions (hint: search for the current year)
  # see https://phpunit.de/supported-versions.html
  - compat

variables:
  COMPOSER_CACHE_DIR: /var/composer
  PHP__memory_limit: 1024M
  PHP_VERSION: "7.4" # use this in doubt

cache:
  key: global
  paths:
    - /var/composer

.base: &base
  before_script:
    - composer require phpunit/phpunit:$PHPUNIT_VERSION
    - composer install # because downloading WP may have deleted plugins
    # prevent artifacts upload from failing
    - touch phpunit-report.xml

  artifacts:
    when: always
    expire_in: 30 days
    expose_as: "CI"
    reports:
      junit: phpunit-report.xml
    paths:
      - composer.json

test: &test
  <<: *base
  image: pretzlaw/php:${PHP_VERSION}-apache
  script:
    - phpdbg -qrr vendor/bin/phpunit
      --coverage-clover coverage.xml
      --log-junit phpunit-report.xml
  parallel:
    matrix:
      - PHP_VERSION: "7.3" # Until 6 Dec 2021
        PHPUNIT_VERSION: "6.0.0"
      - PHP_VERSION: "7.4" # Until 28 Nov 2022
        PHPUNIT_VERSION: "6.0.0"

#
# Compatibility
#
.compat: &compat
  <<: *test
  stage: compat
  needs: [test]

deprecated:
  <<: *compat
  parallel:
    matrix:
      # Deprecated PHP versions but we try keeping it up
      - PHP_VERSION: "7.0"
        PHPUNIT_VERSION: "6.0.0"
      - PHP_VERSION: "7.1"
        PHPUNIT_VERSION: "6.0.0"
      - PHP_VERSION: "7.2"
        PHPUNIT_VERSION: "6.0.0"

upcoming:
  <<: *compat
  allow_failure: true
  parallel:
    matrix:
      # must have
      - PHP_VERSION: "8.0" # Until 28 Nov 2022
      # should have, because WP still supports it so we try this too
      - PHP_VERSION: "5.6"
      # Just curious, if it would fail with the upcoming WP version
      - PHPUNIT_VERSION: "dev-master"

housekeeping:
  <<: *base
  stage: qa
  allow_failure: true # we just want to be informed about this
  script:
    - composer validate --strict --no-check-lock
    - composer outdated --direct
    - test -z $(composer outdated --minor-only)
